{{- if and .Values.s3.enabled (eq .Values.s3.authMode "secret") .Values.s3.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cl.s3SecretName" . }}
  namespace: {{ include "cl.namespace" . }}
  labels:
{{ include "cl.labels" . | indent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | quote }}
  AWS_REGION: {{ .Values.aws.region | quote }}
  AWS_S3_BUCKET: {{ .Values.s3.bucket | quote }}
{{- end }}
